# application-local.yml
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/redroja-realm

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: rest
              uri: http://localhost:8082
              predicates:
                - Path=/api/rest/**
              filters:
                - RewritePath=/api/rest/(?<segment>.*), /${segment}

            - id: documentos
              uri: http://localhost:8083
              predicates:
                - Path=/api/documentos/**
              filters:
                - RewritePath=/api/documentos/(?<segment>.*), /${segment}
          default-filters:                     # <- nivel correcto
            - name: RequestRateLimiter        # mapeado a Spring Cloud Gateway 4.3.0+
              args:
                key-resolver: "#{@principalOrIpKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1
                deny-empty-key: true