#################################################################
# 0 ▸ Ancla para logging por Fluent Bit                         #
#################################################################
x-logging: &fluentd-logging
  logging:
    driver: fluentd
    options:
      fluentd-address: tcp://host.docker.internal:24224
      tag: app.{{.Name}}
      fluentd-async: "true"

#################################################################
# 1 ▸ Servicios de logging + almacenamiento inmutable           #
#################################################################
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --address ":9000" --console-address ":9001" --compat
    environment:
      MINIO_ROOT_USER:     ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    networks: [logs-net]
    ports: ["9000:9000", "9001:9001"]
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  minio-init:
   image: minio/mc:latest          # trae el binario mc
   container_name: minio-init
   networks: [logs-net]
   depends_on:
     minio:
       condition: service_healthy  # espera a que MinIO responda 200/OK
   environment:
     MINIO_ROOT_USER:     ${MINIO_ROOT_USER}
     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
   volumes:
     - ./create_buckets.sh:/create_buckets.sh:ro
   entrypoint: /create_buckets.sh
   restart: "no"

  fluentbit:
    image: cr.fluentbit.io/fluent/fluent-bit:3.0
    container_name: fluentbit
    ports: ["24224:24224"]
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - buffers:/buffers
    networks: [logs-net]
    depends_on:
      minio-init:
        condition: service_completed_successfully
    environment:
      AWS_ACCESS_KEY_ID:     ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}

#################################################################
# 2 ▸ Bases de datos                                            #
#################################################################
  mysql-db-nucleo:
    <<: *fluentd-logging
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_DB_NUCLEO_CONTAINER}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_NUCLEO_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DB_NUCLEO_NAME}
    volumes:
      - ${MYSQL_DB_NUCLEO_VOLUME}:/var/lib/mysql
    ports: ["${MYSQL_DB_NUCLEO_PORT_EXTERNAL}:${MYSQL_DB_NUCLEO_PORT_INTERNAL}"]
    networks: [logs-net, nucleo-db-net]
    restart: always

  postgres-db-email:
    <<: *fluentd-logging
    image: postgres:${POSTGRES_VERSION}
    container_name: ${POSTGRES_DB_EMAIL_CONTAINER}
    environment:
      POSTGRES_USER:     ${POSTGRES_USER_EMAIL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_EMAIL}
      POSTGRES_DB:       ${POSTGRES_DB_EMAIL}
    volumes:
      - ${POSTGRES_DB_EMAIL_VOLUME}:/var/lib/postgresql/data
    ports: ["${POSTGRES_DB_EMAIL_PORT_EXTERNAL}:${POSTGRES_DB_EMAIL_PORT_INTERNAL}"]
    networks: [logs-net, email-db-net]
    restart: always

  keycloak-db:
    <<: *fluentd-logging
    image: ${KEYCLOAK_DB_IMAGE}
    container_name: ${KEYCLOAK_DB_CONTAINER}
    environment:
      POSTGRES_DB:       ${KEYCLOAK_DB_NAME}
      POSTGRES_USER:     ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks: [logs-net, keycloak-network]
    restart: always

  postgres-db-documentos:
    <<: *fluentd-logging
    image: postgres:${POSTGRES_VERSION}
    container_name: ${POSTGRES_DB_DOCUMENTOS_CONTAINER}
    environment:
      POSTGRES_DB:       ${POSTGRES_DB_DOCUMENTOS}
      POSTGRES_USER:     ${POSTGRES_USER_DOCUMENTOS}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DOCUMENTOS}
    volumes:
      - ${POSTGRES_DB_DOCUMENTOS_VOLUME}:/var/lib/postgresql/data
    ports: ["${POSTGRES_DB_DOCUMENTOS_PORT_EXTERNAL}:${POSTGRES_DB_DOCUMENTOS_PORT_INTERNAL}"]
    networks: [logs-net, documentos-db-net]
    restart: always

#################################################################
# 3 ▸ Micro-servicios (prefijo red-roja-)                       #
#################################################################
  red-roja-nucleo:
    <<: *fluentd-logging
    image: dgo95/red-roja:nucleo
    container_name: ${RED_ROJA_NUCLEO_CONTAINER}
    depends_on: [mysql-db-nucleo]
    environment:
      MYSQL_HOST: ${MYSQL_DB_NUCLEO_CONTAINER}
      MYSQL_DATABASE: ${MYSQL_DB_NUCLEO_NAME}
      CJC_FRONT: ${CJC_FRONT}
      AUTH_SERVICE_URI: ${AUTH_SERVICE_URI}
      REST_SERVICE_URI: ${REST_SERVICE_URI}
      DOCUMENTOS_SERVICE_URI: ${DOCUMENTOS_SERVICE_URI}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks: [logs-net, nucleo-db-net, common-net]
    ports: ["${RED_ROJA_NUCLEO_PORT_EXTERNAL}:${RED_ROJA_NUCLEO_PORT_INTERNAL}"]
    restart: always

  red-roja-email:
    <<: *fluentd-logging
    image: dgo95/red-roja:correo
    container_name: ${RED_ROJA_EMAIL_CONTAINER}
    depends_on: [postgres-db-email, kafka]
    environment:
      POSTGRES_HOST: ${POSTGRES_DB_EMAIL_CONTAINER}
      POSTGRES_PORT: ${POSTGRES_DB_EMAIL_PORT_INTERNAL}
      POSTGRES_DB:   ${POSTGRES_DB_EMAIL}
      POSTGRES_USER: ${POSTGRES_USER_EMAIL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_EMAIL}
      CJC_FRONT: ${CJC_FRONT}
      AUTH_SERVICE_URI: ${AUTH_SERVICE_URI}
      REST_SERVICE_URI: ${REST_SERVICE_URI}
      DOCUMENTOS_SERVICE_URI: ${DOCUMENTOS_SERVICE_URI}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks: [logs-net, email-db-net, common-net]
    ports: ["${RED_ROJA_EMAIL_PORT_EXTERNAL}:${RED_ROJA_EMAIL_PORT_INTERNAL}"]
    restart: always

  red-roja-documentos:
    <<: *fluentd-logging
    image: dgo95/red-roja:documentos
    container_name: ${RED_ROJA_DOCUMENTOS_CONTAINER}
    depends_on: [postgres-db-documentos]
    environment:
      POSTGRES_HOST:     ${POSTGRES_DB_DOCUMENTOS_CONTAINER}
      POSTGRES_PORT:     ${POSTGRES_DB_DOCUMENTOS_PORT_INTERNAL}
      POSTGRES_DB:       ${POSTGRES_DB_DOCUMENTOS}
      POSTGRES_USER:     ${POSTGRES_USER_DOCUMENTOS}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DOCUMENTOS}
      CJC_FRONT: ${CJC_FRONT}
      AUTH_SERVICE_URI: ${AUTH_SERVICE_URI}
      REST_SERVICE_URI: ${REST_SERVICE_URI}
      DOCUMENTOS_SERVICE_URI: ${DOCUMENTOS_SERVICE_URI}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    volumes:
      - ${CJC_DOCUMENTOS_VOLUME_FOTOS}:/app/data/fotosPerfil
      - ${CJC_DOCUMENTOS_VOLUME_DOCS}:/app/data/documentos
    networks: [logs-net, documentos-db-net, common-net]
    ports: ["${RED_ROJA_DOCUMENTOS_PORT_EXTERNAL}:${RED_ROJA_DOCUMENTOS_PORT_INTERNAL}"]
    restart: always

  red-roja-gateway:
    <<: *fluentd-logging
    image: dgo95/red-roja:gateway
    container_name: ${RED_ROJA_GATEWAY_CONTAINER}
    environment:
      JWT_SECRET: ${JWT_SECRET}
      CJC_FRONT:  ${CJC_FRONT}
      AUTH_SERVICE_URI: ${AUTH_SERVICE_URI}
      REST_SERVICE_URI: ${REST_SERVICE_URI}
      DOCUMENTOS_SERVICE_URI: ${DOCUMENTOS_SERVICE_URI}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks: [logs-net, common-net]
    ports: ["${RED_ROJA_GATEWAY_PORT_EXTERNAL}:${RED_ROJA_GATEWAY_PORT_INTERNAL}"]
    restart: always

  red-roja-frontend:
    <<: *fluentd-logging
    image: dgo95/red-roja:frontend
    container_name: ${RED_ROJA_FRONTEND_CONTAINER}
    depends_on: [red-roja-gateway]
    networks: [logs-net, common-net]
    ports: ["${RED_ROJA_FRONTEND_PORT_EXTERNAL}:${RED_ROJA_FRONTEND_PORT_INTERNAL}"]
    restart: always

#################################################################
# 4 ▸ Keycloak y demás infraestructura                          #
#################################################################
  keycloak:
    <<: *fluentd-logging
    image: ${KEYCLOAK_IMAGE}
    container_name: ${KEYCLOAK_CONTAINER}
    depends_on: [keycloak-db]
    command: ["start-dev","--http-relative-path=/"]
    environment:
      KC_DB:          postgres
      KC_DB_URL:      jdbc:postgresql://${KEYCLOAK_DB_CONTAINER}:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HOSTNAME:    ${KEYCLOAK_HOSTNAME}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_EVENTS_ENABLED: "true"
      KC_EVENTS_LISTENERS: jboss-logging
      KC_EVENTS_STORE: database
    volumes:
      - ./keycloak-data:/opt/keycloak/data/import
      - ./themes:/opt/keycloak/themes:ro
      - ./providers:/opt/keycloak/providers
    networks: [logs-net, keycloak-network, common-net]
    ports: ["${KEYCLOAK_PORT_EXTERNAL}:${KEYCLOAK_PORT_INTERNAL}"]
    restart: always

  smtp4dev:
    <<: *fluentd-logging
    image: rnwood/smtp4dev:latest
    container_name: ${SMTP4DEV_CONTAINER}
    volumes:
      - ${SMTP4DEV_VOLUME}:/smtp4dev
    networks: [logs-net, common-net]
    ports:
      - "${SMTP4DEV_PORT_SMTP_EXTERNAL}:${SMTP4DEV_PORT_SMTP_INTERNAL}"
      - "${SMTP4DEV_PORT_WEB_EXTERNAL}:${SMTP4DEV_PORT_WEB_INTERNAL}"
    restart: always

  zookeeper:
    <<: *fluentd-logging
    image: ${ZOOKEEPER_IMAGE}
    container_name: ${ZOOKEEPER_CONTAINER}
    networks: [logs-net, common-net]
    ports: ["${ZOOKEEPER_PORT_EXTERNAL}:${ZOOKEEPER_PORT_INTERNAL}"]
    restart: always

  kafka:
    <<: *fluentd-logging
    image: ${KAFKA_IMAGE}
    container_name: ${KAFKA_CONTAINER}
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT:           ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_ADVERTISED_HOST_NAME:        ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ADVERTISED_PORT:             ${KAFKA_ADVERTISED_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    volumes:
      - ${KAFKA_VOLUME}:/kafka
    networks: [logs-net, common-net]
    ports:
      - "${KAFKA_PORT_EXTERNAL}:${KAFKA_PORT_INTERNAL}"
      - "${KAFKA_PORT_EXTERNAL_INTERNAL}:${KAFKA_PORT_INTERNAL_INTERNAL}"
    restart: always

#################################################################
# 5 ▸ Redes y volúmenes                                         #
#################################################################
networks:
  default: { name: logs-net }
  logs-net:          { driver: bridge }
  nucleo-db-net:     { driver: bridge }
  email-db-net:      { driver: bridge }
  documentos-db-net: { driver: bridge }
  keycloak-network:  { driver: bridge }
  common-net:        { driver: bridge }

volumes:
  minio-data:
  buffers:
  keycloak-db-data:
    external: true
    name: desktop_keycloak-db-data
